### ISSUE TITLE
A Build Issue

### ISSUE THREAD

**Issue by iminkin** [dentearl/mafJoin#1]
I tried to build the library, bot got following:

'''
../sonLib/lib/sonLib.a(hashTableC.o): In function `create_hashtable':
/home/iminkin/Program/progressiveCactus/submodules/sonLib/C/impl/hashTableC.c:61: undefined reference to`ceilf'
../sonLib/lib/sonLib.a(hashTableC.o): In function `hashtable_expand':
/home/iminkin/Program/progressiveCactus/submodules/sonLib/C/impl/hashTableC.c:132: undefined reference to`ceilf'
collect2: ld returned 1 exit status
make: **\* [bin/mafJoin] Error 1
'''

I use sonLib that comes with the progressiveCactus distribution (Cactus builds and runs ok).

**Comment by dentearl** [comment]
This looks like an issue with sonLib, not with mafJoin. If you think it's an issue with mafJoin can you provide more context from the error? If you think it's an issue with sonLib, you can open an issue against it at https://github.com/benedictpaten/sonLib/ .

**Comment by iminkin** [comment]
I agree that it is more likely to be a sonLib issue. About context: I can upload the whole virtual image so you can reproduce the error.

**Comment by dentearl** [comment]
Just the full output of the Makefile should be sufficient for me, no disk
image necessary. It could be a compiler flag issue on the mafJoin side of
things.

**Comment by iminkin** [comment]
Stdout:

cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/mafJoin.o.tmp obj/mafJoin.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/jkmaf.o.tmp obj/jkmaf.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/genome.o.tmp obj/genome.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/mafTree.o.tmp obj/mafTree.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnComp.o.tmp obj/malnComp.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnBlk.o.tmp obj/malnBlk.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnBlkCursor.o.tmp obj/malnBlkCursor.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnBlkSet.o.tmp obj/malnBlkSet.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnSet.o.tmp obj/malnSet.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnJoinBlks.o.tmp obj/malnJoinBlks.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnJoinWithinSet.o.tmp obj/malnJoinWithinSet.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnJoinSets.o.tmp obj/malnJoinSets.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnMergeComps.o.tmp obj/malnMergeComps.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnMultiParents.o.tmp obj/malnMultiParents.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnCompCompMap.o.tmp obj/malnCompCompMap.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$
mv obj/malnAdjust.o.tmp obj/malnAdjust.o
cc -O3 -g -Wall -Werror --pedantic -funroll-loops -lm -DNDEBUG -I ../sonLib/lib -I ./src -I /home/iminkin/lib/kent/src/inc -std=c99 -$

Stderr:                                

../sonLib/lib/sonLib.a(hashTableC.o): In function `create_hashtable':
/home/iminkin/Program/progressiveCactus/submodules/sonLib/C/impl/hashTableC.c:61: undefined reference to`ceilf'
../sonLib/lib/sonLib.a(hashTableC.o): In function `hashtable_expand':
/home/iminkin/Program/progressiveCactus/submodules/sonLib/C/impl/hashTableC.c:132: undefined reference to`ceilf'
collect2: ld returned 1 exit status
make: **\* [bin/mafJoin] Error 1

**Comment by dentearl** [comment]
Issue fixed in sonLib, please reopen if other issues persist. Closing.
